Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd

data = pd.read_clipboard()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mParserError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-1-0c52a0041ebb>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0mdata[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_clipboard[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/anaconda3/lib/python3.8/site-packages/pandas/io/clipboards.py[0m in [0;36mread_clipboard[0;34m(sep, **kwargs)[0m
[1;32m     73[0m         )
[1;32m     74[0m [0;34m[0m[0m
[0;32m---> 75[0;31m     [0;32mreturn[0m [0mread_csv[0m[0;34m([0m[0mStringIO[0m[0;34m([0m[0mtext[0m[0;34m)[0m[0;34m,[0m [0msep[0m[0;34m=[0m[0msep[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     76[0m [0;34m[0m[0m
[1;32m     77[0m [0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36mread_csv[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)[0m
[1;32m    684[0m     )
[1;32m    685[0m [0;34m[0m[0m
[0;32m--> 686[0;31m     [0;32mreturn[0m [0m_read[0m[0;34m([0m[0mfilepath_or_buffer[0m[0;34m,[0m [0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    687[0m [0;34m[0m[0m
[1;32m    688[0m [0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36m_read[0;34m(filepath_or_buffer, kwds)[0m
[1;32m    456[0m [0;34m[0m[0m
[1;32m    457[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 458[0;31m         [0mdata[0m [0;34m=[0m [0mparser[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mnrows[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    459[0m     [0;32mfinally[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    460[0m         [0mparser[0m[0;34m.[0m[0mclose[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36mread[0;34m(self, nrows)[0m
[1;32m   1194[0m     [0;32mdef[0m [0mread[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mnrows[0m[0;34m=[0m[0;32mNone[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1195[0m         [0mnrows[0m [0;34m=[0m [0m_validate_integer[0m[0;34m([0m[0;34m"nrows"[0m[0;34m,[0m [0mnrows[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1196[0;31m         [0mret[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_engine[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mnrows[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1197[0m [0;34m[0m[0m
[1;32m   1198[0m         [0;31m# May alter columns / col_dict[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36mread[0;34m(self, rows)[0m
[1;32m   2581[0m             [0mcontent[0m [0;34m=[0m [0mcontent[0m[0;34m[[0m[0;36m1[0m[0;34m:[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m   2582[0m [0;34m[0m[0m
[0;32m-> 2583[0;31m         [0malldata[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_rows_to_cols[0m[0;34m([0m[0mcontent[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2584[0m         [0mdata[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_exclude_implicit_index[0m[0;34m([0m[0malldata[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2585[0m [0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36m_rows_to_cols[0;34m(self, content)[0m
[1;32m   3233[0m                     [0mmsg[0m [0;34m+=[0m [0;34m". "[0m [0;34m+[0m [0mreason[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3234[0m [0;34m[0m[0m
[0;32m-> 3235[0;31m                 [0mself[0m[0;34m.[0m[0m_alert_malformed[0m[0;34m([0m[0mmsg[0m[0;34m,[0m [0mrow_num[0m [0;34m+[0m [0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3236[0m [0;34m[0m[0m
[1;32m   3237[0m         [0;31m# see gh-13320[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36m_alert_malformed[0;34m(self, msg, row_num)[0m
[1;32m   2994[0m         """
[1;32m   2995[0m         [0;32mif[0m [0mself[0m[0;34m.[0m[0merror_bad_lines[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2996[0;31m             [0;32mraise[0m [0mParserError[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2997[0m         [0;32melif[0m [0mself[0m[0;34m.[0m[0mwarn_bad_lines[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2998[0m             [0mbase[0m [0;34m=[0m [0;34mf"Skipping line {row_num}: "[0m[0;34m[0m[0;34m[0m[0m

[0;31mParserError[0m: Expected 2 fields in line 6, saw 9. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.
ParserError: Expected 2 fields in line 6, saw 9. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

